name: server
description: TODO server application built with Dart and MongoDB
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  equatable: ^2.0.5
  stack_trace: ^1.11.1
  dart_jsonwebtoken: ^2.12.2
  mongo_dart: ^0.10.0
  envied: ^0.5.3
  crypto: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
